databases:
  - name: pra_djnago
    region: singapore
    plan: free
    databaseName: pra_djnago_db
    user: django_user

services:
  - type: web
    name: pra_djnago
    env: python
    region: singapore
    buildCommand: './build.sh'
    startCommand: 'gunicorn pra_django.wsgi:application'
    plan: free
    branch: main
    healthCheckPath: /
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pra_djnago_db
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4
    autoDeploy: true